apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-score-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: fraud-score-gke@fraud-score-503823.iam.gserviceaccount.com
